 
echo root = "." > .air.toml
echo testdata_dir = "testdata" >> .air.toml
echo tmp_dir = "tmp" >> .air.toml
echo. >> .air.toml
echo [build] >> .air.toml
echo   bin = "./tmp/main.exe" >> .air.toml
echo   cmd = "go build -o ./tmp/main.exe ./cmd/server" >> .air.toml
echo   delay = 1000 >> .air.toml
echo   exclude_dir = ["assets", "tmp", "vendor", "testdata"] >> .air.toml
echo   exclude_file = [] >> .air.toml
echo   exclude_regex = ["_test.go"] >> .air.toml
echo   include_ext = ["go", "tpl", "tmpl", "html"] >> .air.toml
echo   kill_delay = "0s" >> .air.toml
echo   log = "build-errors.log" >> .air.toml
echo   send_interrupt = false >> .air.toml
echo   stop_on_root = false >> .air.toml
